/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MantenedorProductos;

//import Conexion.ConexionDB
//import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import yourcolor.Conexion;
import yourcolor.Limitador;

/**
 *
 * @author Kampu
 */
public class Productos extends javax.swing.JInternalFrame {
    
            Conexion conexion = new Conexion();
            Connection cn = conexion.conectar();
            DefaultComboBoxModel ModCbx = new DefaultComboBoxModel();
            
    public Productos() {
        initComponents();
        //Productos f = new Productos();
        //f.setBackground(new Color(19,50,67));
        SNumeros(tfCodigo);
        SNumeros(tfStock);
        SNumeros(tfCosto);
        SNumeros(tfUtilidad);
        Cargar();
        limitar();
        btnModificar.setEnabled(false);
        comboProv();
        comboCat();
    }
//Metodo que limita los caracteres de los Txt Field
    public void limitar(){
        tfCodigo.setDocument(new Limitador(tfCodigo, 12));
        tfNombre.setDocument(new Limitador(tfNombre, 30));
        tfStock.setDocument(new Limitador(tfStock, 7));
        tfCosto.setDocument(new Limitador(tfCosto, 10));
        tfUtilidad.setDocument(new Limitador (tfUtilidad,10));
        tfNeto.setDocument(new Limitador(tfNeto, 10));
        tfIva.setDocument(new Limitador(tfIva, 5));
        tfVenta.setDocument(new Limitador(tfVenta, 10));
        jtfDescripcion.setDocument(new Limitador(jtfDescripcion, 60));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        tfCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCosto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        tfImagen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfUtilidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfStock = new javax.swing.JTextField();
        tfIva = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfNeto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfDescripcion = new javax.swing.JTextArea();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfBusqueda = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();
        cbxCategoria = new javax.swing.JComboBox();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(30, 149, 185));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MANTENEDOR DE PRODUCTOS");
        jLabel4.setToolTipText("");

        jLabel1.setText("Codigo");

        cbxProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        cbxProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProveedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio Costo");

        jLabel5.setText("Categoria");

        jLabel6.setText("Imagen");

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel10.setText("Stock");

        jLabel11.setText("Proveedor");

        jLabel12.setText("Descripcion");

        jLabel13.setText("Utilidad");

        tfIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIvaActionPerformed(evt);
            }
        });

        jLabel14.setText("IVA");

        jLabel7.setText("Precio Neto");

        jLabel8.setText("Precio Venta");

        jtfDescripcion.setColumns(20);
        jtfDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtfDescripcion);

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Proveedor", "Nombre", "Stock", "P. Costo", "Utilidad", "P. Neto", "I.V.A", "P. Venta", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(jTable1);

        btnBusqueda.setText("BUSCAR");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfUtilidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(tfIva, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addComponent(cbxProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(138, 138, 138))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 97, Short.MAX_VALUE)
                        .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cbxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(9, 9, 9)
                        .addComponent(tfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /******************************SOLO NUMEROS********************************/
    public void SNumeros (JTextField a){
    //permite hacer la llamada al evento
        //KeyAdapter es una clase abstracta que se adapta para recibir los eventos del teclado
        a.addKeyListener(new KeyAdapter() {
            //Evento a utilizar
            public void keyTyped(KeyEvent e){
            //La variable char extrae la variable que se ingresa
                char c=e.getKeyChar();
                if(Character.isLetter(c)){
                //Sonido en caso que se ingrese un caracter no admitido
                getToolkit().beep();
                e.consume();
                }
            }
        });
    }
    /****************************FIN SOLO NUMEROS******************************/ 
    
    /**************************LLENAR CBX PROVEEDOR****************************/
        public void comboProv() {
            try {
                //ABRIR CONEXION
                conexion.conectar();
                Statement st = cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                ResultSet rs = st.executeQuery("SELECT nombre FROM proveedores");
                ModCbx.addElement("Seleccione un campo");//es el primer registro q mostrara el combo
                cbxProveedor.setModel(ModCbx);//con esto lo agregamos al objeto al jcombobox
                while (rs.next()) {
                    ModCbx.addElement(rs.getObject("nombre"));
                    cbxProveedor.setModel(ModCbx);
                }
                st.close();
                //CERRAR CONEXION
                conexion.desconectar();
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
                
    /************************FIN LLENAR CBX PROVEEDOR**************************/
        
    /**************************LLENAR CBX CATEGORIA****************************/
    public void comboCat() {
            try {
                //ABRIR CONEXION
                conexion.conectar();
                Statement st = cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                ResultSet rs = st.executeQuery("SELECT nombre FROM categorias");
                ModCbx.addElement("Seleccione un campo");//es el primer registro q mostrara el combo
                cbxCategoria.setModel(ModCbx);//con esto lo agregamos al objeto al jcombobox
                while (rs.next()) {
                    ModCbx.addElement(rs.getObject("nombre"));
                    cbxCategoria.setModel(ModCbx);
                }
                st.close();
                //CERRAR CONEXION
                conexion.desconectar();
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    /************************FIN LLENAR CBX CATEGORIA**************************/
    
    /*********************************CALCULOS*********************************/
    public void Calculos(){

        float costo         =0;
        float utilidad      =0;
        float PorcUtilidad  =0;
        float neto          =0;
        float iva           =0;
        float venta         =0;
        
        String costoX;
        String utilidadX;
        String PorcUtilidadX;
        String netoX    =   null;
        String ivaX     =   null;
        String ventaX   =   null;
        
        costoX          =   tfCosto.getText();
        utilidadX       =   tfUtilidad.getText();
        
        costo           =   Integer.parseInt(costoX);
        utilidad        =   Integer.parseInt(utilidadX);
        neto            =   Integer.parseInt(netoX);
        iva             =   Integer.parseInt(ivaX);
        venta           =   Integer.parseInt(ventaX);
        
        PorcUtilidad    =   (costo*utilidad)/100;
        neto            =   (costo+PorcUtilidad);
        iva             =   (neto*19)/100;
        venta           =   (iva+neto);
        
        PorcUtilidadX   =   String.valueOf(PorcUtilidad);
        netoX           =   String.valueOf(neto);
        ivaX            =   String.valueOf(iva);
        ventaX          =   String.valueOf(venta);
        
        tfNeto.setText(netoX);
        tfIva.setText(ivaX);
        tfVenta.setText(ventaX);

    }
    /*******************************FIN CALCULOS*******************************/
    
    /*********************************CARGAR***********************************/
        public void Cargar(){
        //tomar modelo de la tabla
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            //abrir conexion
            conexion.conectar();
        try {
                //Crear consulta para buscar empleado segun rut
                String Query = "select * from productos";
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(Query);
                while(rs.next())
                {
                    String codigo = rs.getString("Codigo");
                    String proveedor = rs.getString("Proveedor");
                    String nombre = rs.getString("Nombre");
                    String stock = rs.getString("Stock");
                    String costo = rs.getString("P_Ccosto");
                    String utilidad = rs.getString("Utilidad");
                    String neto = rs.getString("P_Neto");
                    String iva = rs.getString("IVA");
                    String venta = rs.getString("P_Venta");
                    String categoria = rs.getString("Categoria");
                    String descripcion = rs.getString("Descripcion");
                    Object fila[] = {codigo, proveedor, nombre, stock, costo, utilidad, neto, iva, venta, categoria, descripcion};
                    m.addRow(fila);
                }
                //CERRAR CONEXION
                conexion.desconectar();

            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
        
    /********************************FIN CARGAR********************************/
    
    /********************************LIMPIAR***********************************/
    public void Limpiar(){
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Proveedor", "Nombre", "Stock", "P. Costo", "Utilidad", "P. Neto", "I.V.A", "P. Venta", "Categoria"
            }
        ));
    }
    /*****************************FIN LIMPIAR**********************************/

    /****************************LIMPIAR CAMPOS********************************/  
            public void LimpiarCampos()
        {
            this.tfCodigo.setText("");
            this.tfNombre.setText("");
            this.tfStock.setText("");
            this.tfCosto.setText("");
            this.tfUtilidad.setText("");
            this.tfNeto.setText("");
            this.tfIva.setText("");
            this.tfVenta.setText("");
            this.jtfDescripcion.setText("");
            this.tfBusqueda.setText("");
            this.tfCodigo.requestFocus();
        }
    /**************************FIN LIMPIAR CAMPOS******************************/
            
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
        //abrir nueva conexion
        conexion.conectar();
        //armar query
        String Query = "Insert into productos (codigo, proveedor, nombre, stock, pCosto, utilidad, pNeto, iva, pVenta, categoria, detalle) values ('" + tfCodigo.getText() + "','" + cbxProveedor.getSelectedItem() + "','" + tfNombre.getText() + "','" + tfStock.getText() + "','" + tfCosto.getText() + "','"+tfUtilidad.getText()+"','"+tfNeto.getText()+"','"+tfIva.getText()+"','"+tfVenta.getText()+"','"+cbxCategoria.getSelectedItem()+"','"+jtfDescripcion.getText()+"');";
        //ejecutar query
        Statement statement=(Statement) cn.createStatement();
        statement.executeUpdate(Query);
        Calculos();
        //cerrar conexion
        conexion.desconectar();
        //limpiar tabla
        Limpiar();
        //actualizar
        Cargar();
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        conexion.conectar();
        try {
            PreparedStatement pst = cn.prepareStatement("UPDATE productos SET codigo='"+tfCodigo.getText()+"',nombre='"+tfNombre.getText()+"',stock='"+tfStock.getText()+"',pCosto='"+tfCosto.getText()+"',utilidad='"+tfUtilidad.getText()+"',pNeto='"+tfNeto.getText()+"',iva='"+tfIva.getText()+"',pVenta='"+tfVenta.getText()+"',detalle='"+jtfDescripcion.getText()+"' WHERE codigo='"+tfCodigo.getText()+"'");
            pst.executeUpdate();
                    
            Limpiar();
        } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        //Seleccionar Fila
        int CodSelect = jTable1.getSelectedRow();
        String Numero = m.getValueAt(CodSelect, 0).toString();
        
        int confirmado = JOptionPane.showConfirmDialog(this,"¿Desear realmente eliminar este registro?");

         if (JOptionPane.OK_OPTION == confirmado){
            try {
                //abrir conexion
                conexion.conectar();
                //query
                String Query = "delete from productos where codigo = '" + Numero + "';";
                Statement st = cn.createStatement();
                st.execute(Query);
                //cerrar conexion
                conexion.desconectar();
                Limpiar();
                Cargar();
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
         }else{
            
         }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        Limpiar();
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        try{
            //abrir conexion
            conexion.conectar();
            //Consulta a ejecutar
            String     sql = ("SELECT productos.codigo, proveedores.nombre as proveedor, productos.nombre, productos.stock, "
                    + "productos.pCosto, productos.utilidad, productos.pNeto, productos.iva, productos.pVenta, "
                    + "categorias.nombre as categoria, productos.detalle "
                    + "FROM productos, proveedores, categorias "
                    + "WHERE (productos.proveedor=proveedores.rut) and (productos.categoria=categorias.id) and "
                    + "(codigo like '%"+tfBusqueda.getText()+"%') or (nombre like '%"+tfBusqueda.getText()+"%') or (detalle like '%"+tfBusqueda.getText()+"%')");
            //Preparar la consulta
            Statement st = cn.createStatement();
            //Ejecutar consulta
            ResultSet rs = st.executeQuery(sql);
            //Mostrar los datos
            while(rs.next()){
                String codigo = rs.getString("codigo");
                String proveedor = rs.getString("proveedor");
                String nombre = rs.getString("nombre");
                String stock = rs.getString("stock");
                String costo = rs.getString("pCosto");
                String utilidad = rs.getString("utilidad");
                String neto = rs.getString("pNeto");
                String iva = rs.getString("iva");
                String venta = rs.getString("pVenta");
                String categoria = rs.getString("categoria");
                String descripcion = rs.getString("detalle");
                Object fila[] = {codigo, proveedor, nombre, stock, costo, utilidad, neto, iva, venta, categoria, descripcion};
                m.addRow(fila);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void cbxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProveedorActionPerformed

    private void tfIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIvaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow() ;
        if(fila>=0){
            tfCodigo.setText(jTable1.getValueAt(fila, 0).toString());
            //cbxProveedor.setText(jTable1.getValueAt(fila, 1).toString());
            tfNombre.setText(jTable1.getValueAt(fila, 2).toString());
            tfStock.setText(jTable1.getValueAt(fila, 3).toString());
            tfCosto.setText(jTable1.getValueAt(fila, 4).toString());
            tfUtilidad.setText(jTable1.getValueAt(fila, 5).toString());
            tfNeto.setText(jTable1.getValueAt(fila, 6).toString());
            tfIva.setText(jTable1.getValueAt(fila, 7).toString());
            tfVenta.setText(jTable1.getValueAt(fila, 8).toString());
            //cbxCategoria.setText(jTable1.getValueAt(fila, 9).toString());
            jtfDescripcion.setText(jTable1.getValueAt(fila, 10).toString());
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione una fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cbxCategoria;
    private javax.swing.JComboBox cbxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jtfDescripcion;
    private javax.swing.JTextField tfBusqueda;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCosto;
    private javax.swing.JTextField tfImagen;
    private javax.swing.JTextField tfIva;
    private javax.swing.JTextField tfNeto;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfStock;
    private javax.swing.JTextField tfUtilidad;
    private javax.swing.JTextField tfVenta;
    // End of variables declaration//GEN-END:variables
}
