/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yourcolor;

import Estadisticas.gananciasanuales;
import Estadisticas.gananciasdiarias;
import Estadisticas.gananciasmensuales;
import Estadisticas.ventasmensuales;
import Estadisticas.linea;
import Estadisticas.productosanuales;
import Estadisticas.productosdiarios;
import Estadisticas.productosmensuales;

import Estadisticas.torta;
import Estadisticas.ventasanuales;
import Estadisticas.ventasdiarias;
import MantenedorUsuarios.frmUsuarios;
import MantenedorEstados.frmEstado;
import java.awt.Color;
import java.beans.PropertyVetoException;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;



/**
 *
 * @author Kampu
 */
public class MenuEstadisticas extends javax.swing.JFrame {
 ventasanuales vanu =new ventasanuales();
 productosmensuales prodmen =new productosmensuales();
 productosdiarios proddiarios =new productosdiarios();
 productosanuales prodanual =new productosanuales();
 ventasmensuales venbar =new ventasmensuales();
 ventasdiarias ventadiarias =new ventasdiarias();
 gananciasanuales ganuales =new gananciasanuales();
 gananciasmensuales bar =new gananciasmensuales();
 gananciasdiarias gandiari =new gananciasdiarias();   
 
    /**
     * Creates new form Menu
     */
    public MenuEstadisticas() {
        initComponents();
this.getContentPane().setBackground(Color.DARK_GRAY);
this.setExtendedState(MAXIMIZED_BOTH);
                panelRound1.add(vanu);
                panelRound1.add(prodmen);
                panelRound1.add(proddiarios);
                panelRound1.add(prodanual);
                panelRound1.add(venbar);
                panelRound1.add(ventadiarias);
                panelRound1.add(ganuales);
                panelRound1.add(bar);
                panelRound1.add(gandiari); 
                
            /*   vanu.setVisible(false);
                prodmen.setVisible(false);
                proddiarios.setVisible(false);
                prodanual.setVisible(false);
                venbar.setVisible(false);
                ventadiarias.setVisible(false);
                ganuales.setVisible(false);
                bar.setVisible(false);
                gandiari.setVisible(false);*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new javax.swing.JDesktopPane();
        jSeparator2 = new javax.swing.JSeparator();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction2 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction3 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction4 = new org.edisoncor.gui.button.ButtonAction();
        jSeparator3 = new javax.swing.JSeparator();
        buttonAction5 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction6 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction7 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction8 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction9 = new org.edisoncor.gui.button.ButtonAction();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);

        panelRound1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelRound1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelHeader1.setText("Estadisticas");
        labelHeader1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 50)); // NOI18N

        buttonAction1.setText("Ganancias Diarias");
        buttonAction1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });

        buttonAction2.setText("Ganancias Mensuales");
        buttonAction2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction2ActionPerformed(evt);
            }
        });

        buttonAction3.setText("Ganancias Anuales");
        buttonAction3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAction3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction3ActionPerformed(evt);
            }
        });

        buttonAction4.setText("Ventas Diarias");
        buttonAction4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAction4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction4ActionPerformed(evt);
            }
        });

        buttonAction5.setText("Ventas Mensuales");
        buttonAction5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAction5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction5ActionPerformed(evt);
            }
        });

        buttonAction6.setText("Ventas Anuales");
        buttonAction6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAction6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction6ActionPerformed(evt);
            }
        });

        buttonAction7.setText("TopProductos Anuales");
        buttonAction7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAction7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction7ActionPerformed(evt);
            }
        });

        buttonAction8.setText("TopProductos Diarios");
        buttonAction8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAction8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction8ActionPerformed(evt);
            }
        });

        buttonAction9.setText("TopProductos Mensuales");
        buttonAction9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonAction9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 1578, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonAction1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAction2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAction5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAction3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAction4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAction9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAction7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAction8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAction6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(buttonAction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAction2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAction3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAction4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAction5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAction6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAction8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAction9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAction7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 423, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
    
           vanu.setVisible(false);
                prodmen.setVisible(false);
                proddiarios.setVisible(false);
                prodanual.setVisible(false);
                venbar.setVisible(false);
                ventadiarias.setVisible(false);
                ganuales.setVisible(false);
                bar.setVisible(false);
      
        
     try {
                 

         gandiari.setMaximum(true);
     } catch (PropertyVetoException ex) {
         Logger.getLogger(MenuEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
     }
        gandiari.show();
     
               
    }//GEN-LAST:event_buttonAction1ActionPerformed

    private void buttonAction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction2ActionPerformed
        
vanu.setVisible(false);
                prodmen.setVisible(false);
                proddiarios.setVisible(false);
                prodanual.setVisible(false);
                venbar.setVisible(false);
                ventadiarias.setVisible(false);
                ganuales.setVisible(false);
                gandiari.setVisible(false);
                             
try {
                 

         bar.setMaximum(true);
     } catch (PropertyVetoException ex) {
         Logger.getLogger(MenuEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
     }        bar.show();
        
       
    }//GEN-LAST:event_buttonAction2ActionPerformed

    private void buttonAction3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction3ActionPerformed
        // TODO add your handling code here:
        
        vanu.setVisible(false);
                prodmen.setVisible(false);
                proddiarios.setVisible(false);
                prodanual.setVisible(false);
                venbar.setVisible(false);
                ventadiarias.setVisible(false);
                bar.setVisible(false);
                gandiari.setVisible(false);
        
try {
                 

         ganuales.setMaximum(true);
     } catch (PropertyVetoException ex) {
         Logger.getLogger(MenuEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
     }        ganuales.show();
    }//GEN-LAST:event_buttonAction3ActionPerformed

    private void buttonAction4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction4ActionPerformed
        // TODO add your handling code here:
        vanu.setVisible(false);
                prodmen.setVisible(false);
                proddiarios.setVisible(false);
                prodanual.setVisible(false);
                venbar.setVisible(false);
                ganuales.setVisible(false);
                bar.setVisible(false);
                gandiari.setVisible(false);
try {
                 

         ventadiarias.setMaximum(true);
     } catch (PropertyVetoException ex) {
         Logger.getLogger(MenuEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
     }        ventadiarias.show();
    }//GEN-LAST:event_buttonAction4ActionPerformed

    private void buttonAction5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction5ActionPerformed
        // TODO add your handling code here:
        vanu.setVisible(false);
                prodmen.setVisible(false);
                proddiarios.setVisible(false);
                prodanual.setVisible(false);
                ventadiarias.setVisible(false);
                ganuales.setVisible(false);
                bar.setVisible(false);
                gandiari.setVisible(false);
try {
                 

         venbar.setMaximum(true);
     } catch (PropertyVetoException ex) {
         Logger.getLogger(MenuEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
     }        venbar.show();
    }//GEN-LAST:event_buttonAction5ActionPerformed

    private void buttonAction6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction6ActionPerformed
        // TODO add your handling code here:
                prodmen.setVisible(false);
                proddiarios.setVisible(false);
                prodanual.setVisible(false);
                venbar.setVisible(false);
                ventadiarias.setVisible(false);
                ganuales.setVisible(false);
                bar.setVisible(false);
                gandiari.setVisible(false);
try {
                 

         vanu.setMaximum(true);
     } catch (PropertyVetoException ex) {
         Logger.getLogger(MenuEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
     }        vanu.show();
    }//GEN-LAST:event_buttonAction6ActionPerformed

    private void buttonAction7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction7ActionPerformed
        // TODO add your handling code here:
        vanu.setVisible(false);
                prodmen.setVisible(false);
                proddiarios.setVisible(false);
                venbar.setVisible(false);
                ventadiarias.setVisible(false);
                ganuales.setVisible(false);
                bar.setVisible(false);
                gandiari.setVisible(false);
        try {
                 

         prodanual.setMaximum(true);
     } catch (PropertyVetoException ex) {
         Logger.getLogger(MenuEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
     }
        prodanual.show();
    }//GEN-LAST:event_buttonAction7ActionPerformed

    private void buttonAction8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction8ActionPerformed
        // TODO add your handling code here:
         vanu.setVisible(false);
                prodmen.setVisible(false);
                prodanual.setVisible(false);
                venbar.setVisible(false);
                ventadiarias.setVisible(false);
                ganuales.setVisible(false);
                bar.setVisible(false);
                gandiari.setVisible(false);
try {
                 

         proddiarios.setMaximum(true);
     } catch (PropertyVetoException ex) {
         Logger.getLogger(MenuEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
     }
proddiarios.show();
    }//GEN-LAST:event_buttonAction8ActionPerformed

    private void buttonAction9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction9ActionPerformed
        // TODO add your handling code here:
        vanu.setVisible(false);
                proddiarios.setVisible(false);
                prodanual.setVisible(false);
                venbar.setVisible(false);
                ventadiarias.setVisible(false);
                ganuales.setVisible(false);
                bar.setVisible(false);
                gandiari.setVisible(false);
try {
                 

         prodmen.setMaximum(true);
     } catch (PropertyVetoException ex) {
         Logger.getLogger(MenuEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
     }    
prodmen.show();
    }//GEN-LAST:event_buttonAction9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEstadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private org.edisoncor.gui.button.ButtonAction buttonAction2;
    private org.edisoncor.gui.button.ButtonAction buttonAction3;
    private org.edisoncor.gui.button.ButtonAction buttonAction4;
    private org.edisoncor.gui.button.ButtonAction buttonAction5;
    private org.edisoncor.gui.button.ButtonAction buttonAction6;
    private org.edisoncor.gui.button.ButtonAction buttonAction7;
    private org.edisoncor.gui.button.ButtonAction buttonAction8;
    private org.edisoncor.gui.button.ButtonAction buttonAction9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private javax.swing.JDesktopPane panelRound1;
    // End of variables declaration//GEN-END:variables

    
}
