/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yourcolor;

import Estadisticas.ventasmensuales;
import MantenedorPerfiles.Perfiles;
import Ventas.frmVentas;
import Ventas.variables;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static yourcolor.Login.txtrut;

/**
 *
 * @author Administrador
 */
public class PPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PPrincipal
     */
    public PPrincipal() throws SQLException {
        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);
        labelRut.setText(Login.txtrut.getText());
        
        try {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
        } catch (SQLException ex) {
            Logger.getLogger(ventasmensuales.class.getName()).log(Level.SEVERE, null, ex);
        }
 Connection conexion = null;
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/yourcolor", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(ventasmensuales.class.getName()).log(Level.SEVERE, null, ex);
        }
 //Para ejecutar la consulta
 Statement s = null;
        try {
            s = conexion.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(ventasmensuales.class.getName()).log(Level.SEVERE, null, ex);
        }
        String rut=labelRut.getText();
        variables.Rut = labelRut.getText();
             ResultSet rs = s.executeQuery("SELECT * from usuarios where (rut='"+rut+"')");
                      
         
         while (rs.next()) {//mientras tenga registros que haga lo siguiente
                        //contenido
                             System.out.println(rs.getString("nombres"));
                            labelNombre.setText(rs.getString("nombres")+" "+rs.getString("apellidos"));
                            lblperfil1.setText(rs.getString("perfil"));

                            switch(rs.getInt("perfil"))
        {
            case 2:
                           lblperfil.setText("Empleado");
                break;
            case 3:
                            lblperfil.setText("Administrador");            
                            break;
             case 4:
                            lblperfil.setText("Bodeguero");
                            break;
        }

                        }
         
       if(Integer.parseInt(lblperfil1.getText())==2){
btn3.setEnabled(false);
System.out.println("HABILITADO");
        }else if(Integer.parseInt(lblperfil1.getText())==4){
btn1.setEnabled(false);
btn2.setEnabled(false);

System.out.println("HABILITADO");
        }
       
    }
    
       //Instancias de pantallas internas
       frmVentas PVentas = new frmVentas();
       Perfiles PPerfiles = new Perfiles();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblperfil = new javax.swing.JLabel();
        lblperfil1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        Dp = new javax.swing.JDesktopPane();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        labelRut = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 3, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, -1));

        lblperfil.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        lblperfil.setForeground(new java.awt.Color(204, 204, 204));
        lblperfil.setText("jLabel2");
        getContentPane().add(lblperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 110, 36));

        lblperfil1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        lblperfil1.setForeground(new java.awt.Color(204, 204, 204));
        lblperfil1.setText("jLabel2");
        getContentPane().add(lblperfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 42, -1));

        btn1.setText("Perfiles");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 100, 40));

        btn2.setText("Mensajes");
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 100, 40));

        btn3.setText("Usuarios");
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 100, 40));
        getContentPane().add(Dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1240, 570));

        btn4.setText("Proveedores");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 100, 40));

        btn5.setText("Estados");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 100, 40));

        btn6.setText("Estadisticas");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 70, 100, 40));

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 100, 40));

        btn8.setText("Productos");
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 100, 40));

        btn9.setText("Categorias");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 100, 40));

        btn10.setText("Pedidos");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, 100, 40));

        labelRut.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelRut.setForeground(new java.awt.Color(204, 204, 204));
        labelRut.setText("jLabel2");
        getContentPane().add(labelRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        labelNombre.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(204, 204, 204));
        labelNombre.setText("jLabel3");
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        this.Dp.add(PPerfiles);
        this.PVentas.dispose();
        this.PPerfiles.setVisible(true);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10ActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
       Dp.add(PVentas);
       PPerfiles.dispose();
       PVentas.setVisible(true);
    }//GEN-LAST:event_btnVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Dp;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRut;
    public static javax.swing.JLabel lblperfil;
    public static javax.swing.JLabel lblperfil1;
    // End of variables declaration//GEN-END:variables
}
